config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "categories#index"

  resources :categories, except: [:edit, :update, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe, presence: true
  validates :category, presence: true
  validates :recipe_id, uniqueness: { scope: :category_id }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :categories, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, format: { with: /\A\d(\.\d{1})?\z/, message: 'must have at most one decimal place' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/bookmarks/new.html.erb
<div class="new-recipe">
  <%= simple_form_for [@category, @bookmark] do |f|%>
  <h4>Add a recipe to <%= @category.name %></h4>
  <%= f.input :comment %>
  <%= f.association :recipe %>
  <%= f.submit %>
  <% end %>
</div>

app/views/categories/index.html.erb
 <%= render 'shared/banner' %>
 <%= render 'shared/cards' %>

app/views/categories/new.html.erb
<div class="categories-new">

  <%= simple_form_for(@category) do |f| %>
  <h4>Add a new category</h4>
    <%= f.input :name, label: false, input_html: { placeholder: "The category name..." } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/categories/show.html.erb
<%= render 'shared/banner_recipe' %>
<%= render 'shared/recipe_cards' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/recipes/show.html.erb
<h1> <%= @recipe.name %> </h1>

<img src="<%= @recipe.image_url %>" alt="<%= @recipe.name %>">
<p><%= @recipe.description %> </p>
<h3>Rating: <%= @recipe.rating %> </h3>

<%= link_to "Back to Cookbook", categories_path , class: "btn btn-primary" %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url('<%= image_path 'banner.jpg' %>')">
  <div>
    <h1>CookBook </h1>
    <h3>Save your favourite recipes </h3>
  </div>
</div>

app/views/shared/_banner_recipe.html.erb
<div class="banner" style="background-image: url('<%= image_path 'italian.jpg' %>')">
  <div>
    <h1><%= @category.name %> </h1>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="container">
  <div class="header-btn">
    <h3> List of Categories </h3>
    <p> <%=link_to "Add New Category", new_category_path %></p>
  </div>

  <div class="card-wrapper">
    <% @categories.each do |category| %>
      <%= link_to category_path(category), class: "card-link" do %>
        <div class="card-texts">
        <div class="card" style="background: linear-gradient(rgba(0, 0, 0, 0.2)), url('<%= asset_path(category.image_url.presence || "default.jpg") %>'); background-size: cover; background-position: center; position: relative;">
          <h1><%= category.name %></h1>
          <h4><%= "#{category.recipes.count} recipes" %></h4>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
<%= image_tag("cookbook_logo.png") %>
  <div class="buttons">
  <%= link_to "Home", root_path %>
  <%= link_to "New Category", new_category_path%>
  </div>
</div>

app/views/shared/_recipe_cards.html.erb
<div class="container">
  <div class="header-btn">
    <h3>Recipes</h3>
    <p><%= link_to "Add New Recipe", new_category_bookmark_path(@category) %></p>
  </div>

  <div class="cards">
    <% @category.bookmarks.each do |bookmark| %>
      <%= link_to recipe_path(bookmark.recipe), class: "card-link" do %>
        <div class="card">
          <div class="card-recipe">
            <img src="<%= bookmark.recipe.image_url %>" alt="<%= bookmark.recipe.name %>" />
          </div>

          <div class="card-description">
            <h3><%= bookmark.recipe.name %></h3>
            <p><%= bookmark.recipe.description %></p>
          </div>

          <div class="card-bottom">
            <div class="card-infos">
              <p><%= bookmark.comment %></p>
            </div>

            <div class="ratings">
              <% rating = bookmark.recipe.rating.floor %>
              <p>
                <%= "⭐" * rating %> (<%= bookmark.recipe.rating %>)
              </p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>